#!/usr/bin/env bash
# Downloads the tiny Android build toolchain used by build.sh.
#
#   * OpenJDK 21 runtime  -> the "jdk4py" python wheel (it ships a JRE)
#   * aapt2               -> the "aapt2" python wheel (Linux binary)
#   * d8, apksigner, ecj, android.jar -> bundled in the npm package @drxiaozhi/minapk
#
# Everything lands in ~/.toolchain (outside the repository, so nothing big is
# ever committed). Total download is about 70 MB.
set -euo pipefail

TC="${TOOLS_DIR:-$HOME/.toolchain}"
BIN="$TC/bin"
VENV="$TC/venv"

echo "toolchain: $TC"
mkdir -p "$BIN"

if [ ! -x "$VENV/bin/python" ]; then
    echo "== creating virtualenv =="
    python3 -m venv "$VENV"
fi

if [ ! -x "$VENV/lib/python3.11/site-packages/jdk4py/java-runtime/bin/java" ] &&
   [ ! -e "$TC/java" ]; then
    echo "== installing jdk4py + aapt2 =="
    "$VENV/bin/pip" install --quiet --upgrade pip
    "$VENV/bin/pip" install --quiet "jdk4py==21.0.8.2" "aapt2==0.2.1" "pillow"
fi

need_jars=0
for f in d8.jar apksigner.jar ecj-3.45.0.jar android.jar; do
    [ -f "$BIN/$f" ] || need_jars=1
done

if [ "$need_jars" = "1" ]; then
    echo "== downloading android build tools (d8 / ecj / apksigner / android.jar) =="
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    url="https://registry.npmjs.org/@drxiaozhi/minapk/-/minapk-0.4.0.tgz"
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$url" -o "$tmp/minapk.tgz"
    else
        wget -q -O "$tmp/minapk.tgz" "$url"
    fi
    tar xzf "$tmp/minapk.tgz" -C "$tmp" package/tools
    cp "$tmp/package/tools/d8.jar" \
       "$tmp/package/tools/apksigner.jar" \
       "$tmp/package/tools/ecj-3.45.0.jar" \
       "$tmp/package/tools/android.jar" "$BIN/"
fi

# point env.sh at whatever python version the venv picked
PY=$(ls -d "$VENV"/lib/python3.*/site-packages 2>/dev/null | head -1)
if [ -z "$PY" ]; then
    echo "!! could not locate the virtualenv site-packages" >&2
    exit 1
fi

cat > "$TC/env.sh" <<EOF
# generated by fetch-tools.sh
export TC="$TC"
export JAVA_HOME="$PY/jdk4py/java-runtime"
export AAPT2="$PY/aapt2/bin/Linux/aapt2"
export ANDROID_JAR="$TC/bin/android.jar"
export ECJ="$TC/bin/ecj-3.45.0.jar"
export D8="$TC/bin/d8.jar"
export APKSIGNER="$TC/bin/apksigner.jar"
export PATH="\$JAVA_HOME/bin:\$PATH"
EOF

echo "== done =="
ls -la "$BIN"
